-- Reclaim data foundation upgrade.
-- Additive and safe to re-run. It does not drop user data.
--
-- Purpose:
-- 1. Make the repository's clean-install path match the tables the frontend expects.
-- 2. Preserve production's canonical profiles.quit_date column while remaining compatible
--    with older schemas that used profiles.quit_at.
-- 3. Add durable daily check-ins with idempotent client IDs and strict RLS.

create extension if not exists pgcrypto;

-- Production uses quit_date. Older schema.sql revisions used quit_at.
alter table public.profiles add column if not exists quit_date timestamptz;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'profiles'
      and column_name = 'quit_at'
  ) then
    execute 'update public.profiles set quit_date = coalesce(quit_date, quit_at) where quit_date is null';
  end if;
end $$;

-- A clean schema historically did not create smoking_events even though the app and
-- upgrade_existing_schema.sql expect it to exist.
create table if not exists public.smoking_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  smoked_at timestamptz not null default now(),
  cigarettes numeric(8,2) not null default 1 check (cigarettes > 0),
  reason text,
  created_at timestamptz not null default now(),
  event_type text not null default 'smoked' check (event_type in ('smoked','craving')),
  resisted boolean,
  toolkit text,
  duration_seconds integer check (duration_seconds >= 0),
  tool_feedback text check (tool_feedback in ('yes','a_little','not_really'))
);

alter table public.smoking_events add column if not exists event_type text not null default 'smoked';
alter table public.smoking_events add column if not exists resisted boolean;
alter table public.smoking_events add column if not exists toolkit text;
alter table public.smoking_events add column if not exists duration_seconds integer;
alter table public.smoking_events add column if not exists tool_feedback text;
create index if not exists smoking_events_user_created_idx on public.smoking_events (user_id, created_at desc);
create index if not exists smoking_events_user_type_time_idx on public.smoking_events (user_id, event_type, smoked_at desc);

-- The frontend hydrates this table and falls back to its built-in evidence timeline if
-- no rows have been curated yet. Keep medical copy/content separate from schema setup.
create table if not exists public.health_milestones (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  minutes_after_quitting bigint not null check (minutes_after_quitting >= 0),
  source_name text,
  source_url text,
  created_at timestamptz not null default now()
);
create index if not exists health_milestones_minutes_idx on public.health_milestones (minutes_after_quitting);
alter table public.health_milestones enable row level security;
revoke all on table public.health_milestones from anon, authenticated;
grant select on table public.health_milestones to anon, authenticated;
drop policy if exists "Anyone can view health milestones" on public.health_milestones;
drop policy if exists "health milestones readable" on public.health_milestones;
create policy "health milestones readable"
  on public.health_milestones for select
  to anon, authenticated
  using (true);

-- Daily mood check-ins were local-only in production. client_id makes browser retries
-- idempotent and supports later cross-device hydration without duplicate entries.
create table if not exists public.daily_checkins (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid,
  mood text not null check (mood in ('great','okay','struggling','craving')),
  note text,
  created_at timestamptz not null default now()
);

alter table public.daily_checkins add column if not exists client_id uuid;
alter table public.daily_checkins add column if not exists note text;
update public.daily_checkins set client_id = gen_random_uuid() where client_id is null;
alter table public.daily_checkins alter column client_id set not null;
create unique index if not exists daily_checkins_user_client_uidx on public.daily_checkins (user_id, client_id);
create index if not exists daily_checkins_user_created_idx on public.daily_checkins (user_id, created_at desc);

alter table public.daily_checkins enable row level security;
revoke all on table public.daily_checkins from anon, authenticated;
grant select, insert on table public.daily_checkins to authenticated;

drop policy if exists "own checkins" on public.daily_checkins;
drop policy if exists "daily checkins select own" on public.daily_checkins;
drop policy if exists "daily checkins insert own" on public.daily_checkins;

create policy "daily checkins select own"
  on public.daily_checkins for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "daily checkins insert own"
  on public.daily_checkins for insert
  to authenticated
  with check ((select auth.uid()) = user_id);
