import { SUPABASE_URL, SUPABASE_KEY } from './config.js';
const $ = (s, root=document) => root.querySelector(s);
const STORAGE='reclaim-state-v2', SESSION='reclaim-session-v1', THEME_STORAGE='reclaim-theme-v1';
let theme=localStorage.getItem(THEME_STORAGE)==='light'?'light':'dark';
function applyTheme(next=theme){theme=next==='light'?'light':'dark';document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=theme==='light'?'#f8f6fc':'#000000'}
if(new URLSearchParams(location.search).get('theme-preview')==='light')theme='light';
applyTheme();
const now = new Date();
const COUNTRIES=[['IN','India','INR','en-IN'],['US','United States','USD','en-US'],['GB','United Kingdom','GBP','en-GB'],['CA','Canada','CAD','en-CA'],['AU','Australia','AUD','en-AU'],['NZ','New Zealand','NZD','en-NZ'],['AE','United Arab Emirates','AED','en-AE'],['SA','Saudi Arabia','SAR','en-SA'],['QA','Qatar','QAR','en-QA'],['SG','Singapore','SGD','en-SG'],['MY','Malaysia','MYR','en-MY'],['JP','Japan','JPY','ja-JP'],['CN','China','CNY','zh-CN'],['KR','South Korea','KRW','ko-KR'],['PH','Philippines','PHP','en-PH'],['ID','Indonesia','IDR','id-ID'],['TH','Thailand','THB','th-TH'],['VN','Vietnam','VND','vi-VN'],['PK','Pakistan','PKR','en-PK'],['BD','Bangladesh','BDT','bn-BD'],['LK','Sri Lanka','LKR','en-LK'],['NP','Nepal','NPR','en-NP'],['ZA','South Africa','ZAR','en-ZA'],['NG','Nigeria','NGN','en-NG'],['KE','Kenya','KES','en-KE'],['BR','Brazil','BRL','pt-BR'],['MX','Mexico','MXN','es-MX'],['AR','Argentina','ARS','es-AR'],['CH','Switzerland','CHF','de-CH'],['SE','Sweden','SEK','sv-SE'],['NO','Norway','NOK','nb-NO'],['DK','Denmark','DKK','da-DK'],['PL','Poland','PLN','pl-PL'],['TR','Turkey','TRY','tr-TR'],['IL','Israel','ILS','he-IL'],['DE','Germany','EUR','de-DE'],['FR','France','EUR','fr-FR'],['ES','Spain','EUR','es-ES'],['IT','Italy','EUR','it-IT'],['NL','Netherlands','EUR','nl-NL']];
const STAGE_CIRCLES=[
  {key:'first72',id:'00000000-0000-0000-0000-000000000010',label:'First 72h',title:'FIRST 72 HOURS',min:0,max:2,copy:'Stay close. Focus on the next small decision.'},
  {key:'firstWeek',id:'00000000-0000-0000-0000-000000000011',label:'First week',title:'FIRST WEEK',min:3,max:6,copy:'Compare notes with people building their first rhythm.'},
  {key:'firstMonth',id:'00000000-0000-0000-0000-000000000012',label:'First month',title:'FIRST MONTH',min:7,max:29,copy:'Protect new routines and make progress visible.'},
  {key:'beyond',id:'00000000-0000-0000-0000-000000000001',label:'30+ days',title:'30 DAYS & BEYOND',min:30,max:Infinity,copy:'Keep growing—and leave a light on for people behind you.'}
];
const seed={stage:'intro',view:'home',authMode:'signup',profile:{name:'',journeyMode:'quit',quitAt:new Date().toISOString(),cigarettesPerDay:20,dailyTarget:15,pricePerPack:300,cigarettesPerPack:20,minutesPerCigarette:11,country:'IN',currency:'₹',currencyCode:'INR',attemptNumber:1,bestStreakSeconds:0},smokingEvents:[],checkins:[],cravings:[],goals:[{id:'camera',name:'New Camera',target:15000}],posts:[{id:'maya-story',userId:'seed-maya',initial:'M',name:'Maya',days:31,text:'One month today. The difficult evenings became easier when I stopped trying to fight the whole future and focused on the next ten minutes.',topic:'win',circleId:'00000000-0000-0000-0000-000000000001',cheers:18,cheered:false,featured:true,replyCount:2,createdAt:new Date(now-2*36e5).toISOString()},{id:'rohan-story',userId:'seed-rohan',initial:'R',name:'Rohan',days:9,text:'Walked through my usual smoke break today. Small win, but it felt huge.',topic:'win',circleId:'00000000-0000-0000-0000-000000000012',cheers:11,cheered:false,replyCount:1,createdAt:new Date(now-5*36e5).toISOString()}],replies:[{id:'seed-reply-1',postId:'maya-story',userId:'seed-nia',name:'Nia',text:'The next ten minutes idea helped me tonight. Thank you.',createdAt:new Date(now-70*60e3).toISOString()},{id:'seed-reply-2',postId:'maya-story',userId:'seed-omar',name:'Omar',text:'One decision at a time. Congratulations on the month.',createdAt:new Date(now-35*60e3).toISOString()},{id:'seed-reply-3',postId:'rohan-story',userId:'seed-maya',name:'Maya',text:'Changing the usual break routine is a huge win.',createdAt:new Date(now-3*36e5).toISOString()}],savedPostIds:[],blockedUsers:[],reportedTargets:[],communityReports:[],communityFilter:'all',communityView:'feed',communityStage:null,communityStageTouched:false,challengeCompletions:[]};
let state=load(); let session=loadSession(); let breathing=null; let cravingTimer=null;
const previousVisitAt=state.lastVisitAt||null;
state.lastVisitAt=new Date().toISOString();
save();
const isOAuthReturn=new URLSearchParams(location.hash.slice(1)).has('access_token');
if(!isOAuthReturn)state.stage='intro';
function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
function saveSession(value){session=value;if(value)localStorage.setItem(SESSION,JSON.stringify(value));else localStorage.removeItem(SESSION)}
function authHeaders(){const h={apikey:SUPABASE_KEY,'Content-Type':'application/json'};if(session?.access_token)h.Authorization=`Bearer ${session.access_token}`;return h}
async function refreshSession(){if(!session?.refresh_token)throw new Error('Your session ended. Please sign in again.');const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});const data=await r.json();if(!r.ok||!data.access_token){saveSession(null);throw new Error('Your session ended. Please sign in again.')}saveSession({...session,...data});return data}
async function api(path,options={}){const {_retried,...requestOptions}=options,r=await fetch(`${SUPABASE_URL}${path}`,{...requestOptions,headers:{...authHeaders(),...(requestOptions.headers||{})}});const body=await r.text();let data;try{data=body?JSON.parse(body):null}catch{data=body}if(!r.ok){const message=data?.msg||data?.message||data?.error_description||data?.hint||`Request failed (${r.status})`;if((r.status===401||r.status===403)&&!_retried&&session?.refresh_token&&/jwt|token|expired/i.test(message)){await refreshSession();return api(path,{...requestOptions,_retried:true})}throw new Error(message)}return data}
function acceptOAuth(){const p=new URLSearchParams(location.hash.slice(1));if(p.get('access_token')){saveSession({access_token:p.get('access_token'),refresh_token:p.get('refresh_token'),user:null});history.replaceState({},'',location.pathname);state.stage='setup';save()}}
acceptOAuth();
function load(){try{const stored=JSON.parse(localStorage.getItem(STORAGE)||'{}'),loaded={...seed,...stored};delete loaded.celebration;delete loaded.celebratedMilestones;loaded.profile={...seed.profile,...(loaded.profile||{})};loaded.smokingEvents=loaded.smokingEvents||[];loaded.posts=(loaded.posts||[]).map((post,index)=>({...post,topic:post.topic||'win',circleId:post.circleId||circleForDays(+post.days||0).id,createdAt:post.createdAt||new Date(Date.now()-(index+2)*36e5).toISOString(),cheered:!!post.cheered}));loaded.replies=loaded.replies||[];loaded.savedPostIds=loaded.savedPostIds||[];loaded.blockedUsers=loaded.blockedUsers||[];loaded.reportedTargets=loaded.reportedTargets||[];loaded.communityReports=loaded.communityReports||[];loaded.challengeCompletions=loaded.challengeCompletions||[];return loaded}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]))}
// ...
