import test from 'node:test';
import assert from 'node:assert/strict';
import {ensurePlan,dayKey,shiftDay,dailySeries,reviewState,commitReview,journeySummary,journeyCards,overlaySmokingMutations,switchJourney,targetOn} from '../smoking-journey.js';
const start=new Date('2026-08-01T12:00:00');
function fixture(){const s={profile:{journeyMode:'reduce',cigarettesPerDay:20},smokingEvents:[],dayConfirmations:{}};ensurePlan(s,start);return s;}
function week(s,counts,from='2026-08-01'){counts.forEach((count,i)=>{const day=shiftDay(from,i);if(count)s.smokingEvents.push({at:day+'T12:00:00',cigarettes:count});s.dayConfirmations[day]=count?'complete':'smoke_free';});}
const end=new Date('2026-08-08T20:00:00');
test('initial target uses estimate; confirmed recent history takes priority',()=>{const s=fixture();assert.equal(s.reductionPlan.currentTarget,18);delete s.reductionPlan;week(s,[10,10,10,10],'2026-07-25');ensurePlan(s,start);assert.equal(s.reductionPlan.baseline,10);assert.equal(s.reductionPlan.currentTarget,9);});
test('missing, explicitly untracked, partial and today never become review successes',()=>{const s=fixture();week(s,[0,0,0]);s.dayConfirmations['2026-08-04']='untracked';s.smokingEvents.push({at:'2026-08-05T12:00:00',cigarettes:1});s.dayConfirmations['2026-08-08']='smoke_free';assert.equal(reviewState(s,end).status,'collect_more_data');assert.equal(reviewState(s,end).loggedDays,3);assert.equal(commitReview(s,'continue',end),false);});
test('stable stage advances only when due and cannot be applied twice',()=>{const s=fixture();week(s,[16,16,17,18,18,18,18]);assert.equal(commitReview(s,'continue',new Date('2026-08-07T23:59:00')),false);assert.equal(commitReview(s,'continue',end),true);assert.equal(s.reductionPlan.currentTarget,16);assert.equal(s.reductionPlan.stage,2);assert.equal(commitReview(s,'continue',end),false);assert.equal(s.reductionPlan.history.length,1);});
test('mixed week holds; struggling twice offers but never forces +1',()=>{const s=fixture();week(s,[18,18,20,20,20,18,18]);assert.equal(reviewState(s,end).status,'mixed');commitReview(s,'continue',end);assert.equal(s.reductionPlan.currentTarget,18);const t=fixture();week(t,[25,25,25,25,25,25,25]);commitReview(t,'continue',end);week(t,[25,25,25,25,25,25,25],'2026-08-08');const later=new Date('2026-08-15T12:00:00');assert.equal(reviewState(t,later).action,'offer_adjustment');assert.equal(commitReview(t,'continue',later),false);assert.equal(t.reductionPlan.currentTarget,18);assert.equal(commitReview(t,'hold',later),true);assert.equal(t.reductionPlan.currentTarget,18);});
test('accepted struggling adjustment raises by one and floor remains one',()=>{const s=fixture();s.reductionPlan.lastReviewStatus='struggling';week(s,[25,25,25,25]);assert.equal(commitReview(s,'adjust',end),true);assert.equal(s.reductionPlan.currentTarget,19);const t=fixture();t.reductionPlan.currentTarget=1;week(t,[1,1,1,1]);assert.equal(reviewState(t,end).action,'offer_quit_transition');commitReview(t,'continue',end);assert.equal(t.reductionPlan.currentTarget,1);assert.equal(t.profile.journeyMode,'reduce');});
test('Track has no target, quitting metrics or invented empty-day averages',()=>{const s=fixture();s.profile.journeyMode='track';const x=journeySummary(s,end);assert.equal(x.todayProgress,null);assert.equal(x.progress,null);assert.equal(x.average,null);assert.equal(x.hardDay,null);assert.ok(journeyCards(s,end).every(c=>!c.title.includes('target')));});
test('confirmed zero counts, historical targets and gaps break streaks',()=>{const s=fixture();week(s,[0,18,18,18,18,18,18]);let x=journeySummary(s,end);assert.equal(x.consistency,7);assert.equal(x.targetStreak,7);delete s.dayConfirmations['2026-08-07'];x=journeySummary(s,end);assert.equal(x.targetStreak,0);assert.equal(x.consistency,0);});
test('pending edit and deletion overlay cloud records without resurrection',()=>{const a={cloudId:'a',at:'2026-08-01T12:00:00',cigarettes:1},b={...a,cloudId:'b'};const edited={...a,cigarettes:4};assert.deepEqual(overlaySmokingMutations([a,b],{a:{kind:'upsert',event:edited},b:{kind:'delete'}}),[edited]);});
test('local calendar arithmetic works across DST and year boundaries',()=>{assert.equal(shiftDay('2026-12-31',1),'2027-01-01');assert.equal(shiftDay('2026-03-08',1),'2026-03-09');const s=fixture();assert.equal(dailySeries(s,7,end).length,7);});

test('switching away pauses target history; returning starts a fresh review week',()=>{const s=fixture();switchJourney(s,'track',end);assert.equal(targetOn(s.reductionPlan,'2026-08-09'),null);switchJourney(s,'reduce',new Date('2026-08-10T12:00:00'));assert.equal(s.reductionPlan.reviewStart,'2026-08-10');assert.equal(s.reductionPlan.currentTarget,18);assert.equal(targetOn(s.reductionPlan,'2026-08-11'),18);});
